import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.scss';
import {
  SidebarInset,
  SidebarProvider,
  SidebarTrigger,
} from '@/components/ui/sidebar';
import { AppSidebar } from '@/components/app-sidebar';
import { Separator } from '@radix-ui/react-separator';
import { getSession, logout } from '@/lib/session';
import { Button } from '@/components/ui/button';
import Link from 'next/link';

const inter = Inter({
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getSession();

  return (
    <html lang="en">
      <body className={`${inter.className} dark`}>
        <SidebarProvider>
          <AppSidebar />
          <SidebarInset>
            <header className="flex h-16 shrink-0 items-center gap-2 border-b px-4">
              <SidebarTrigger className="-ml-1" />
              <Separator orientation="vertical" className="mr-2 h-4" />
              {/* <Breadcrumb>
                <BreadcrumbList>
                  <BreadcrumbItem className="hidden md:block">
                    <BreadcrumbLink href="#">
                      Building Your Application
                    </BreadcrumbLink>
                  </BreadcrumbItem>
                  <BreadcrumbSeparator className="hidden md:block" />
                  <BreadcrumbItem>
                    <BreadcrumbPage>Data Fetching</BreadcrumbPage>
                  </BreadcrumbItem>
                </BreadcrumbList>
              </Breadcrumb> */}

              {session && (
                <div className="flex gap-2 items-center ml-auto">
                  <span>
                    {' '}
                    <p>{session.email}</p>
                  </span>
                  <Button onClick={logout}>Logout</Button>
                </div>
              )}
              {!session && (
                <Button asChild className="ml-auto">
                  <Link href="/login">Login</Link>
                </Button>
              )}
            </header>
            {children}
            {/* <BottomNavbar /> */}
          </SidebarInset>
        </SidebarProvider>
      </body>
    </html>
  );
}
